registry:
  image: viljaste/registry:dev
  hostname: registry
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - registrydata
  environment:
    - SERVER_NAME=localhost
    - USERNAME=root
    - PASSWORD=root
registrydata:
  image: viljaste/data:dev
  hostname: registrydata
  volumes:
    - /registry
