registry:
  image: viljaste/registry:latest
  hostname: registry
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - registrydata
  environment:
    - SERVER_NAME=localhost
    - TIMEOUT=900
    - USERNAME=root
    - PASSWORD=root
registrydata:
  image: viljaste/data:latest
  hostname: registrydata
  volumes:
    - /registry
